version: '3.8'
services:

  backend:
    depends_on: 
      - db_redis
    container_name: contranscat_backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000 
    environment:
      APP_ENV: local
    volumes:  
      - ./src:/server
    command: > 
      sh -c "npm install && npm run local"

  db_contrans:
    image: mysql:8.0.32
    container_name: contranscat_mysql_db
    restart: unless-stopped
    env_file:
      - src/local.env
    volumes: 
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - 3306:3306

  db_redis:
    image: redis:7.0.11-alpine3.18
    container_name: contranscat_redis_db
    ports:
      - 6379:6379