version: '3.8'
services:

  docker-nodemysql.com:
    build: .
    ports:
      - 80:8000 
    environment:
      NODE_ENV: local

  db_mongo:
    image: mongo:4.4.9
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: baseNode
      MONGO_INITDB_ROOT_PASSWORD: XO9NhmKOfsfAwnUb
    volumes:
      - mongo_data:/data/db
    
volumes:
  mongo_data:
