version: '3.8'
services:

  docker-cotranstcat-backend.com:
    build: .
    ports:
      - 80:8000 
    environment:
      APP_ENV: local
    volumes:
      - ./src:/usr/src

  bd-cotranstcat-mongo:
    image: mongo:5.0.14
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: cotranstcatUser
      MONGO_INITDB_ROOT_PASSWORD: x19l7es5122IUAYe
    volumes:
      - mongo_data:/data/db
    
volumes:
  mongo_data:
